app/build.gradle
Add cardview-v7 to build.gradle to fix "No resource identifier found for... attribute 'cardCornerRadius'" compilation error.
=> Fix broken build because of missing cardview-v7 lib.

app/build.gradle
Plugin 'android' is deprecated and Android Studio suggested the replacement.
=> chore: replace  plugin 'android' with 'com.android.application'

.travis.yml, app/build.gradle
This PR moves the travis build from Java environment to the android one, currently still in beta.
This will hopefully will reduce the build time significantly as there is almost no download required.
More info can be found here: http://docs.travis-ci.com/user/languages/android/
=> Migrate to android environment on Travis rather than java

app/build.gradle, app/src/main/assets/third_party.html, app/src/main/java/org/gdg/frisbee/android/app/App.java, app/src/main/java/org/gdg/frisbee/android/app/GdgVolley.java
To address issue #190 I've removed Chris Bane's Bitmap Cache library from the project and now only Picasso is used for loading images.
When I have more time I'll also change from Volley to Retrofit but I'll work on other things first.
=> Remove Chris Bane's Bitmap Cache library

app/src/main/java/org/gdg/frisbee/android/api/GroupDirectory.java, app/src/main/res/layout/list_pulse_item.xml
And added some padding to the cards in the Pulse list. Normal padding is not the same. Actually we shouldn't use Cards here. The app is over cardified. Should I remove cards here?
=> GDG Pulse is fixed by providing the new JSON url.

app/src/main/res/layout-land/fragment_pulse.xml, app/src/main/res/layout-sw600dp-land/fragment_gdl_list.xml, app/src/main/res/layout-sw800dp-land/fragment_gdl_list.xml, app/src/main/res/layout/activity_arrow_tagged.xml, app/src/main/res/layout/fragment_about_contributors.xml, app/src/main/res/layout/fragment_events.xml, app/src/main/res/layout/fragment_gde_list.xml, app/src/main/res/layout/fragment_list.xml, app/src/main/res/layout/fragment_news.xml, app/src/main/res/layout/fragment_pulse.xml
Some of the lists don't contain touch state but for the ones that do, this fixes ripple effect drawn behind.
=> Ripple effect drawn on top of the items with this flag.

app/build.gradle, app/src/main/assets/third_party.html
NineOldAndroids was used by the old implementation of the pull to refresh pattern.
With the new implementation in PR #186 this library is not needed anymore.
=> Remove NineOldAndroids dependency

app/src/main/java/org/gdg/frisbee/android/provider/GdgProvider.java
With the current develop branch the app crashed on startup for me. Investigation lead to the point in which the content provider tried to access the model cache via the app's instance but this was not created yet so it caused an NPE. 
It seems the onCreate of the content provider is executed before the app's onCreate is done. To avoid such race conditions I moved the init of the content provider's list into the first query. Since this is already off-main thread I could simplify the call into a synchronous call.
With this fix my local version could start again and display the list of GDGs.
=> Fix content provider app crash

app/src/main/java/org/gdg/frisbee/android/Const.java, app/src/main/java/org/gdg/frisbee/android/activity/FirstStartActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/StartActivity.java, app/src/main/java/org/gdg/frisbee/android/service/GcmIntentService.java
- refactor: EXTRA_GROUP_ID refactored into EXTRA_CHAPTER_ID and removed unused "selected_chapter" key
- `MyAdapter` is now `ChapterFragmentPagerAdapter`
- `initChapters()` function is used everywhere to initialize the `ViewPager`. No more duplicates.
- `initChapters()` now gets selectedChapter as a variable. It is given immediately when an orientation change occurs. It can be null. When it is null, it is gotten from Intent Extra.
- `ChapterFragmentPagerAdapter` now gets selectedChapter from constructor and it cannot be null again.
=> Selected chapter cannot be null

app/src/main/assets/third_party.html
ACRA was replaced with Crashlytics.
=> chore: remove ACRA from 3rd party libraries

app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-th/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
This is one of the lint errors. about_tabs should contain 6 items but all of these include 5.
=> about_tabs are removed on other languages.

app/src/main/assets/third_party.html
Joda-Time was removed but it was left in the list of 3rd party libraries.
=> chore: remove Joda-Time from 3rd party libraries

app/src/main/java/org/gdg/frisbee/android/Const.java, app/src/main/java/org/gdg/frisbee/android/activity/GdeActivity.java, app/src/main/res/layout/fragment_gde_list.xml, app/src/main/res/values-sw600dp-land/integers.xml, app/src/main/res/values-sw600dp/integers.xml, app/src/main/res/values-sw720dp-land/integers.xml
GDE column count is updated. 
For tablet landscape it was ugly. 
The new configuration: (Taken from Google IO app) 
phone 2 columns
phone landscape 3
small tablet 3
small tablet landscape 4
big tablet landscape 5
Before:
After:
=> GDE column count

app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeriesFragment.java
It is fine in Lollipop because you can set headers in ListViews in Lollipop whenever you want.
But before lollipop, the header should be set before Adapter initialisation. So the TaggedEventSeries is crashing for all devices below Lollipop. Should we send an update to the play store?
=> [URGENT] Crash fix: ListView header set before adapter is set.

app/src/main/java/org/gdg/frisbee/android/fragment/SettingsFragment.java
**Problem**
App crashes when user selects Home GDG preference before the list of data has been loaded asynchronously.
**Solution**
Disable uninitalized ListPreferneces
=> disable ListPreferences when no data available, fixes #281

app/src/main/java/org/gdg/frisbee/android/fragment/SwipeRefreshRecyclerViewFragment.java
The SwipeRefreshLayout computes if the RecyclerView inside can scroll or not. When you quickly change the layouts, it gets null and the computation gives null pointer exception. The exception is internal in RecyclerView LayoutManager. So I guess this is the only fix.
=> NullPointerException Fix

app/src/main/java/org/gdg/frisbee/android/activity/GdeActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/PulseActivity.java, app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep1Fragment.java
The old code with the crash #298 is like this
```
if (isDetached()) {
Toast.makeText(getActivity(), R.string.fetch_chapters_failed, Toast.LENGTH_SHORT).show();
} else {		
Crouton.makeText(getActivity(), getString(R.string.fetch_chapters_failed), Style.ALERT).show();		
}
```
Crash happens with the `getString` function there. In order that to happen, `isDetached()` should be false meaning that the Fragment is Attached. But the crash says that the fragment is not attached. Damn Fragments!!!
I don't know a permanent solution to this. It is a pain. Whatever you do, you will always have these issues. And they are almost always happen when the user exits the app, without waiting the response (which is obviously fine). 
I would wrap with `try-catch`s all the Crouton's
=> My proposal to fix #298

app/build.gradle, build.gradle
`./gradlew dependencyUpdates -Drevision=release` allows every project contributor to easily generate a report like this
```
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest milestone version:
- com.android.support:appcompat-v7:21.0.3
- com.android.support:cardview-v7:21.0.3
- com.android.support:mediarouter-v7:21.0.3
- com.android.support:recyclerview-v7:21.0.3
- com.android.support:support-v4:21.0.3
- com.android.support.test:testing-support-lib:0.1
- com.android.support.test.espresso:espresso-core:2.0
- com.github.ben-manes:gradle-versions-plugin:0.8
- com.github.triplet.gradle:play-publisher:1.0.2
- …
```
=> Update versions plugin to 0.8, move dep to maven/jcenter

app/src/main/res/layout/fragment_changelog.xml, app/src/main/res/layout/fragment_chapter_info.xml, app/src/main/res/layout/fragment_get_involved.xml
1) Fix: padding issue in details box.
2) Fix: padding issue in change log details textview
3) Fix: padding issue in get involved details layout
=> fix: padding issue

app/src/main/java/org/gdg/frisbee/android/activity/GdgNavDrawerActivity.java
Issue:
When the navigation drawer is open and if you press back key, It closes the application (if home screen) or goes back to the previous screen.
Fix: 
Navigation drawer should be closed on back key press. I have included close navigation drawer code inside the onBackPressed() of GdgNavDrawerActivity, as it's a base activity.
=> fix: Navigation drawer close issue

app/src/main/java/org/gdg/frisbee/android/api/GdgXHub.java, app/src/main/java/org/gdg/frisbee/android/app/App.java
IO Extended section is not working and will not work when it is enabled. We should update the app before May 1st. 
perPage was not working and returning default 25 events. it should be small letters perpage. And appearantly -1 returns all the results
=> fix: ioextended tag was wrong.

app/src/main/java/org/gdg/frisbee/android/app/App.java
There are more events with "i-oextended" tag.
=> fix: IO Extended tag is updated again

app/build.gradle
I saw this `textOutput 'stdout'` in Jake Wharton's U2020 app. While it is useful in Travis, it outputs huge number of warnings in Travis. So I disabled warnings on Travis to clearly see errors on Travis. Does it make sense?
=> experiment: disable warnings on Travis.

app/src/main/java/org/gdg/frisbee/android/Const.java, app/src/main/java/org/gdg/frisbee/android/activity/GdeActivity.java, app/src/main/java/org/gdg/frisbee/android/api/GdeDirectory.java, app/src/main/java/org/gdg/frisbee/android/api/GitHub.java, app/src/main/java/org/gdg/frisbee/android/api/model/ContributorList.java, app/src/main/java/org/gdg/frisbee/android/api/model/GdeList.java, app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java, app/src/main/java/org/gdg/frisbee/android/fragment/ContributorsFragment.java, app/src/main/java/org/gdg/frisbee/android/utils/Utils.java
This PR removes use of ArrayList and instead uses subclasses of ArrayList.
The ModelCache could not restore the component class of lists because the generic type information was in https://github.com/gdg-x/frisbee/blob/1cdbaa6d0c7575ad4eb79ad4762ece6faa8f46ff/app/src/main/java/org/gdg/frisbee/android/utils/Utils.java#L71 was erased.
=> Fix/Model cache for ArrayList

app/src/main/java/org/gdg/frisbee/android/activity/FirstStartActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/GdeActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/GdgNavDrawerActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/PulseActivity.java, app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java, app/src/main/java/org/gdg/frisbee/android/eventseries/EventListFragment.java, app/src/main/java/org/gdg/frisbee/android/eventseries/GdgEventListFragment.java, app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeriesActivity.java, app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeriesFragment.java, app/src/main/java/org/gdg/frisbee/android/fragment/ContributorsFragment.java, app/src/main/java/org/gdg/frisbee/android/fragment/InfoFragment.java, app/src/main/java/org/gdg/frisbee/android/fragment/NewsFragment.java, app/src/main/java/org/gdg/frisbee/android/fragment/PulseFragment.java, app/src/main/res/layout-land/activity_special.xml, app/src/main/res/layout/activity_about.xml, app/src/main/res/layout/activity_event.xml, app/src/main/res/layout/activity_gde.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_pulse.xml, app/src/main/res/layout/activity_special.xml
- "content_frame" id is used to show Croutons.
- This id is present in all layouts as a `FrameLayout`
- For the future, if "content_frame" is not present, Crouton library does not crash, it displays the default behavior. So there wont be any problem.
Future Work:
Change most of the Error Croutons into empty view with an error message. 
Fixes #343
=> Crotuons are now showed below Toolbar and SlidingTabs

app/src/main/java/org/gdg/frisbee/android/activity/GdgNavDrawerActivity.java, app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java, app/src/main/java/org/gdg/frisbee/android/app/OrganizerChecker.java, app/src/main/res/values/strings.xml
Signin Needed dialog support. 
- A dialog is shown to users to take them to sign-in when needed. (It is now when Arrow and Achivements clicked)
- After a succesful login, they are also taken to the item clicked.
Fixes #222 
**Side note:** Cannot login with debug builds. I've tested it with release builds and was working. 
But after openning Arrow page, it couldn't detect that I am an organizer. It was because of a 400 error from googleapis.com. Production work fine.
=> Login dialog

app/src/main/AndroidManifest.xml, app/src/main/java/android/support/v4/preference/PreferenceFragment.java
It also aligns the items with the title as shown in the below screenshot:
=> Removed unnecessary padding in Settings.

app/src/main/java/org/gdg/frisbee/android/Const.java, app/src/main/java/org/gdg/frisbee/android/chapter/LeadFragment.java, app/src/main/res/values/strings.xml
This PR adds another message for chapter leads, it is about the g+ community:
=> Add message for G+ community for leads

README.md, app/build.gradle, app/src/main/java/org/gdg/frisbee/android/Const.java, app/src/main/java/org/gdg/frisbee/android/api/model/OrganizerCheckResponse.java, app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java, app/src/main/java/org/gdg/frisbee/android/chapter/NewsFragment.java, app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java, app/src/main/java/org/gdg/frisbee/android/eventseries/EventListFragment.java, app/src/main/java/org/gdg/frisbee/android/fragment/SettingsFragment.java, app/src/main/java/org/gdg/frisbee/android/gde/GdeAdapter.java
This work began with removing `browser_simple_api_access_key` and it included bunch of stuff. 
- `browser_simple_api_access_key` is removed. 
- `ip_simple_api_access_key` cannot be removed because G+ apis used in `NewsFragment` didn't work with `android_simple_api_access_key`
- Plus APIs used in the app are updated to be used from GMS. Only News Feed requests are done with the Google API Client. I wish we could remove it. 
- And finally got rid of the compiler warning by adding global exclude into configurations.
=> Remove browser api key

app/src/main/java/org/gdg/frisbee/android/Const.java, app/src/main/java/org/gdg/frisbee/android/app/App.java, app/src/main/java/org/gdg/frisbee/android/app/OrganizerChecker.java, app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java, app/src/main/java/org/gdg/frisbee/android/eventseries/GdgEventListFragment.java
- It was caching for 30 days in SharedPrefs. Cache mechanism is completely removed. I can re-add it if someone wants. I don't think it is necessary. New organisers should see them immediately.
- When the currentId is null, which happens on app start, it was making the request. Since the request fails, it thoughts that the user is not organiser.
Fixes #360
=> Organiser Check is fixed

app/src/main/res/layout/fragment_for_leads.xml
Listview divider was visible :)
=> fix: Listview divider in leads tab

app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java
Adds a separator after Arrow menu entry.
Having more separator, e.g. for events is too much especially, if there is only one or two events.
Before | After
---|---
=> 336/Add separator in NavigationView

app/src/main/java/org/gdg/frisbee/android/activity/ParseDeepLinkActivity.java, app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java, app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java, app/src/main/java/org/gdg/frisbee/android/pulse/PulseFragment.java, app/src/main/res/layout-land/fragment_pulse.xml, app/src/main/res/layout/fragment_pulse.xml, app/src/main/res/layout/list_pulse_item.xml
Cards are removed from Pulse page. 
What was the opposite of over-cardifying? I've done that. 
Here are the new look. 
Even on Nexus 6, some chapter names were truncated when it was 3 columns no landscape. It is 2 columns now.
=> Pulse page quick redesign

app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java
- Fixed logic of validating inputs in feedback dialog
- Did minor re-factoring of setting error. Document says "if the error functionality has not been enabled via setErrorEnabled(boolean), then it will be automatically enabled if error is not empty. And If the error is null, the error message will be cleared."
=> fix: minor fix in validate input function

app/src/main/java/org/gdg/frisbee/android/achievements/AchievementActionHandler.java, app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java
This way we stopped calling Achievement unlocking in every Activity start.
This also stops leaking Activities I hope.
I will also help #457 but will not fix it completely.
=> Achievement Unlocks are now stored in SharedPreferences.

app/src/main/java/org/gdg/frisbee/android/common/GdgActivity.java
Listeners are registered in onStart and unregistered in onStop
=> GoogleApiClient hopeful memory leak fix. 

app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java, app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java, app/src/main/java/org/gdg/frisbee/android/pulse/PulseFragment.java
The problem is because FragmentStatePagerAdapter was aggressively caching the states of its children Fragments. 
Here is the bug reported and it is still open. https://code.google.com/p/android/issues/detail?id=37990
There are couple of ways to fix it using a really really custom FragmentStatePagerAdapter without subclassing it. I don't like those solutions. It is not optimal but recreating the adapter fixes this problem. 
The problem is actually because of the positions calculation in the code. On orientation change it reset and makes another problem. I saved it on config change and now it works perfectly. 
Fixes #451
=> Fix pulse numbering bug. 

app/build.gradle, app/src/main/java/org/gdg/frisbee/android/onboarding/StartActivity.java
I've been thinking about this for a long time. 
Google uses these keys for rate limiting and quota purposes. Our API usage does not have quota. 
I have created two new keys in the console for debug builds. Even if they are stolen(!) and used excessively, we can just replace them. It won't affect production too. Does it make sense to you all?
And `play_app_id` was already in the source control in [this file](https://github.com/gdg-x/frisbee/blob/develop/app/src/main/res/values/games-ids.xml). It is also not private. No one can do anything with it. Google makes signature control when it is used. 
Please comment on and correct me if I wrong. 
I erased my `local.properties` file and application worked perfectly.
=> Added keys for debug builds to ease the onboarding experience

app/build.gradle, build.gradle
Joda Time Android requires initialisation with context. Normal jodatime is used for unit tests.
Some common versions numbers of libraries is put the root build.gradle file.
=> Unit test fixed.

app/build.gradle, app/src/dev/java/org/gdg/frisbee/android/app/BaseApp.java, app/src/main/java/org/gdg/frisbee/android/api/model/Chapter.java, app/src/main/java/org/gdg/frisbee/android/api/model/Geo.java, app/src/main/java/org/gdg/frisbee/android/chapter/ChapterComparator.java, app/src/test/java/org/gdg/frisbee/android/chapter/ChapterComparatorTest.java, build.gradle
Test coverage for ChapterComparator is %93 now. It is not %100 because of the wrong `distanceBetween` calculation made in Robolectric implementation.
Geo lat, lng getters are made public for testing.
BTW, targetSdkVersion is set to 21 because Robolectric does not have 22 yet. There is not much difference between 21 and 22 in terms of targetSdkVersion anyways.
=> Tests are added for ChapterComparator.

app/src/main/java/org/gdg/frisbee/android/view/LocationListPreference.java
entries.length gave me NullPointerException since the hub is down now.
There is no need to save the size of the array. writeStringArray already saves the size and handle null state as well.
=> NullPointer fix. 

app/src/main/java/org/gdg/frisbee/android/app/OrganizerChecker.java, app/src/main/java/org/gdg/frisbee/android/arrow/ArrowActivity.java, app/src/main/java/org/gdg/frisbee/android/arrow/OrganizerAdapter.java, app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java, app/src/main/java/org/gdg/frisbee/android/utils/PlusUtils.java
PlusUtils class is introduced. …
Deprecated getCurrentPerson method is only used here.
It checks apiClient if it is connected and has necessary null checks.
- removeUserPicture method is moved inside updateUserPicture
This can be done now because we always have GoogleApiClient connected.
=> Fix plus profile image related crashes. 

README.md, app/build.gradle, build.gradle
The default value for minSdkLevel is always 16. When Travis is publishing Apk to Play Store or we do a release build by command line, it will be 16. 
It can be easily turned to 21/22/23 for faster debug builds by providing `minSdk` property. 
This property can be set using Android Studio compiler settings. 
More info can be found [here](http://artemzin.com/blog/minsdk-without-flavors/)
Fixes #565
=> minSdkVersion is now taken from command line property.

app/src/main/java/org/gdg/frisbee/android/api/PlusApi.java, app/src/main/java/org/gdg/frisbee/android/api/PlusApiFactory.java, app/src/main/java/org/gdg/frisbee/android/api/model/Image.java, app/src/main/java/org/gdg/frisbee/android/api/model/ImageInfo.java, app/src/main/java/org/gdg/frisbee/android/app/App.java, app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java
This PR adds a retrofit service for the Google plus REST API.
It is used to retrieve chapter images in the event details page.
=> 583/Use REST api to retrieve chapter image

app/build.gradle
Since we removed Plus Client, okhttp-urlconnection dependency is not needed anymore.
Fixes #564
=> Remove url connection dependency

settings/proguard/proguard-support-v7-appcompat.pro
According to this, this problem is fixed. I heard somewhere that this can be removed. When it is removed, proguard will save use more space.
https://code.google.com/p/android/issues/detail?id=78377
I've alse searched for this crash in Fabric. We don't have the crash mentioned in the bug report. So it will be safe to remove this.
=> Remove unnecessary proguard rule. 

app/src/main/java/org/gdg/frisbee/android/achievements/AchievementActionHandler.java
This PR fixes #595 by checking for connected `Game.API`
=> 595/Check for connected games api in AchievementActionHandler

app/build.gradle, build.gradle, wear/build.gradle
Wear app now uses the same Timber version.
JodaTime is updated.
=> Fix some dependencies. 

app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java
- selectedPulse cannot be null anymore. It is passed to adapter by the constructor.
- Its default value is GLOBAL
- When we retrieve a Pulse object, `setupPulseScreen` is called.
- `setupPulseScreen` sets up the array, inits the Spinner and selects the default selected value in Spinner.
- `initSpinner` now only inits the Spinner.
- `onItemSelected` checks if the previous selected item is available and then setup the ViewPager with `onPulseItemSelected`
- method ordering is adjust to make it top down readable.
- PulsePagerAdapter is now a static class to prevent Context leaks.
Supposed to fix crash 237
http://crashes.to/s/cdcf7ea59c7
=> Several changes in PulseActivity. 

app/src/main/java/org/gdg/frisbee/android/Const.java
All dates are now UTC.
According to JodaTime, all date time objects should be valid. In some corner cases, because of the daylight saving times, some of them are invalid. When you create the object using UTC timezone, it will always be valid. This will fix crash 230, 264 http://crashes.to/s/3d775ef701f
More info
http://joda-time.sourceforge.net/apidocs/org/joda/time/IllegalInstantException.html
http://stackoverflow.com/questions/4983846/calculating-a-time-duration-with-joda-time
=> Fix crash related to DST

app/src/alpha/java/org/gdg/frisbee/android/app/BaseApp.java, app/src/main/java/org/gdg/frisbee/android/app/App.java, app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java, app/src/main/java/org/gdg/frisbee/android/utils/FileUtils.java
On app update the app now deleted the model cache directory. This will prevent crashes related to model changes in the future. We had a lot of these crashes in the past. 
Fixes crash 262
http://crashes.to/s/b5fd72e0102
=> Remove model cache dir on app update

app/src/main/res/layout-land/activity_special.xml, app/src/main/res/layout/fragment_changelog.xml, app/src/main/res/layout/fragment_event_overview.xml, app/src/main/res/layout/fragment_external_libraries.xml, app/src/main/res/layout/fragment_gde_about.xml, app/src/main/res/layout/header_list_special_event_series.xml
Some TextViews are made selectable for copy & paste. 
Lets discuss about them briefly. We can disable some of them if you like. 
Screens:
- The description about event series like DevFest etc. 
- Changelog
- Event Detail Title
- Event Detail Description
- 3rd party libraries. 
- GDE descriptions. 
Screenshots will be added later. 
Fixes #635
=> Selectable Texts are enabled for various screens

app/build.gradle, app/google-services.json, app/src/main/AndroidManifest.xml, app/src/main/java/org/gdg/frisbee/android/messaging/InstanceIdService.java, app/src/main/java/org/gdg/frisbee/android/messaging/MessagingService.java, app/src/main/res/values/tracker.xml, build.gradle
This PR uses Google Service plugin 3.0 and the firebase configuration for FCM.
This is the preparation for more messaging logic. For now, we can't send messages to users per chapter, just the usual when in background messages. More depends on the backend.
=> Feature/442 Cloud Messaging

app/src/main/java/org/gdg/frisbee/android/gde/GdeActivity.java
I think GDE categories should be displayed in ascending order.
=> sort gde categories in ascending order

app/src/main/res/layout/actionbar_chapter_selector.xml
I was trying to change the chapter in the MainActivity by using just the keyboard. 
Dialog was working fine with the keyboard once it is open. The Chapter swapper was not focusable. I change TextView to Button and now it just works great.
=> Change TextView to Button to make it selectable by keyboard

app/src/main/java/org/gdg/frisbee/android/fragment/SettingsFragment.java
Fix crash related to Play Services.
When we remove the button, the other GCM settings has dependency on this. When it cannot find it, it just crashes.
=> Fix crash in Settings

app/src/main/AndroidManifest.xml
Disable GPS requirement to be able to be installed on Chromebooks
Fixes #649
=> Fix Chromebooks

.buildscript/deploy_alpha.sh
Since we now protect `release` branch, Travis cannot push it.
So the script now tries to merge the current branch back to develop and push the version change there.
=> Fix Travis not being able to push to release branch

app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java, app/src/main/res/layout/card_about_box.xml, app/src/main/res/layout/list_resource_item.xml
Apparently, android:autoLink="all" won't work with html a tags, so we need to set LinkMovementMethod as the MovementMethod programmatically
=> Issue #652: Links in Info page are not clickable

app/src/main/java/org/gdg/frisbee/android/activity/ParseDeepLinkActivity.java
Improve readability of ParseDeepLinkActivity. Remove redundant null checks. Use support annotations to avoid NullPointerException. Resolve Activity before firing implicit intent.
=> refactor:  cleanup ParseDeepLinkActivity

app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java, app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java, app/src/main/java/org/gdg/frisbee/android/chapter/OrganizerLoader.java, app/src/main/res/layout/list_organizer_item.xml
This PR includes a solution that will _hopefully_ make rate limiting 403 API errors lot less. 
I guess the real solution to that would be to bound ou API key to our app signature. When we do that, Google+ API will give us option for more API calls. 
But I also realized that we are loading all the organizers at once. This PR proposes a very simple AsyncTask to load organizers one by one. It will load them synchronously one by one and let the UI know about organizers one by one. 
Throughout the code in `InfoFragment`, I also did lots of refactoring to keep indentation sane. 
Fixes #693
=> Load organizers one by one to avoid rate limit problems

.buildscript/deploy_alpha.sh
Limit automated alpha build whatsnew file generation to 500 chars.
Instead of writing to the file twice, we only write once and in the middle we limit it using `head -c 500`
Fixes #632
=> Limit alpha whats new message to 500 chars

app/src/main/java/org/gdg/frisbee/android/common/GdgActivity.java, app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java, app/src/main/java/org/gdg/frisbee/android/fragment/SettingsFragment.java, app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartActivity.java, app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-hy-rAM/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt-rPT/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-th/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
Currently, since we changed the way we sign in, users updated the app will not be automatically signed in. 
This PR moves sign in logic from NavDrawer back to `GdgActivity`. It is because I want to recover errors in any Activity we are. 
In `GdgActivity`, if our prefs says `isSignedIn` and Google Auth says it is not, we request sign in. 
And also it will first try `silentSignIn` and then normal sign in with a dialog. 
In case of an app update, `silentSignIn` should automatically work and the state will be preserved. 
The other use case is where the user revokes the app in Google privacy settings on the web. After a time, our app will request sign in again with a dialog. If the user really does not want it, they can press cancel and the app will never ask again. 
Also added a …
=> Force sign in after app update
