gdg-x/frisbee

app/build.gradle

It builds and be able to run on my local.
I see the welcome screen but it couldn't get chapters list. I think it is because I dont have keys. 
Lets see if it builds on Travis.

Granular play services libraries are used.

---

app/build.gradle

Sorry guys, 
I have also added appstate. All I want to actually is to fix the errors in the Travis CI build. 
Thank you all.

Appstate is used in the app. It is also added.

---

app/src/main/java/org/gdg/frisbee/android/activity/FirstStartActivity.java
app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep1Fragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep2Fragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep3Fragment.java

While I was trying to figure out what was happening with the fact that chapters where not being fetched, I had my first exploration through the FirstStart* classes and thought I could do a bit of refactoring and code reformatting.
After talking to @stefanhoth he told me that the problem most probably was the fact that the SSL certificate had expired.
I thought it was okay to submit a pull request anyway with the changed I've made.

Some refactoring in the FirstStart* classes

---

app/src/main/java/org/gdg/frisbee/android/adapter/ContributorAdapter.java
app/src/main/java/org/gdg/frisbee/android/fragment/ContributorsFragment.java

* Add copyright message to the top of the file
* Implement ViewHolder pattern
* Use super.addAll if in API >= 10 because it doesn't call notifyDataSetChanged() for each add()
* Replace App.getInstance().getPicasso() with Picasso.with(context) since Picasso is already a singleton

perf: implement ViewHolder pattern in ContributorAdapter

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/gdg/frisbee/android/activity/GdgActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/GdgNavDrawerActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/SettingsActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/StartActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/TrackableActivity.java
app/src/main/java/org/gdg/frisbee/android/fragment/SettingsFragment.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_settings.xml
app/src/main/res/values-v11/gdg_styles.xml
app/src/main/res/values-v21/gdg_themes.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/gdg_styles.xml
app/src/main/res/values/gdg_themes.xml

The main purpose of this PR is to close #164.
I'll implement #174 on top of this one if it gets merged.
Some refactoring and code formatting changes were done along the way while implementing this.

Update action bar to the new Material style

---

app/src/main/java/org/gdg/frisbee/android/utils/ChapterComparator.java

- Instead of keeping a ref to SharedPrefs, ref to HOME GDG is kept.
- MAX_DISTANCE is introduced.
- When we were at San Francisco at the summit, I saw people having difficulties when they are looking for their home gdg. 
- With this commit, only GDGs within 500 KM are sorted with the distance
- Others are sorted alphabetically.
We can change the 500KM max distance but I found that it is enough for most of the countries. I am open to suggestions.

Improvements in ChapterComparator

---

app/build.gradle

Butterknife and Otto are updated

Gradle dependencies tidied.

---

app/build.gradle

With shrinkResources, unused images will be removed automatically.
With resConfigs, only the languages that we support will be included from 3rd party libs.
More info at http://cyrilmottier.com/2014/08/26/putting-your-apks-on-diet/

Grade optimisations

---

app/build.gradle
app/src/main/assets/third_party.html

Update OkHttp from 1.6 to 2.2.0.
Update Picasso to the latest version also.
Add Okio library since according to OkHttp's website:
> You'll also need Okio, which OkHttp uses for fast I/O and resizable buffers.

Update OkHttp and Picasso libraries, add Okio

---

app/src/main/java/org/gdg/frisbee/android/activity/GdgNavDrawerActivity.java

Error implementation should be more beautiful.

fix: Error when arrow drawer item clicked for non login user.

---

.travis.yml
app/build.gradle
app/src/main/java/org/gdg/frisbee/android/adapter/EventAdapter.java
app/src/main/java/org/gdg/frisbee/android/utils/EventDateComparator.java
app/src/test/java/org/gdg/frisbee/android/utils/EventDateComparatorShould.java
build.gradle

This PR adds a simple unit tests for EventDateComparator (and also improves the comparator) by using android gradle plugin 1.1.0

184/Use android build gradle plugin 1.1.0 and add simple junit test

---

app/build.gradle
app/src/main/java/org/gdg/frisbee/android/Const.java
app/src/main/java/org/gdg/frisbee/android/api/OkStack.java
app/src/main/java/org/gdg/frisbee/android/app/App.java

ALPHA and DEVELOPER mode variables are moved to BuildConfig.

Fix warnings in App.java

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/gdg/frisbee/android/activity/GdgActivity.java
app/src/main/java/org/gdg/frisbee/android/event/EventActivity.java
app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java
app/src/main/res/layout/activity_event.xml
app/src/main/res/layout/fragment_event_overview.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Use a white text and blue popup as well
**Solution**

use toolbar for EventActivity, use color references were possible

---

app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/adapter/ChapterAdapter.java
app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep1Fragment.java

fix: change from white to black text on the spinner of the start flow

---

app/build.gradle
app/proguard-rules.txt
app/src/main/assets/third_party.html
app/src/main/java/org/gdg/frisbee/android/app/App.java

They say that this is better in terms of performance.

Joda Time for Android by dlew is used instead of the original.

---

app/src/main/res/values/strings.xml

And translatable="false" added to the event names and the app name.

IO Extended should be 2015

---

app/src/main/res/values/colors.xml

fixes #287
It is not extremely better and it is better.

WTM color change

---

app/src/main/AndroidManifest.xml

This filters devices in Play Store and is not necessary.

---

app/src/main/java/android/support/v4/preference/PreferenceFragment.java
app/src/main/java/org/gdg/frisbee/android/Const.java
app/src/main/java/org/gdg/frisbee/android/activity/FirstStartActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/StartActivity.java
app/src/main/java/org/gdg/frisbee/android/adapter/PulseAdapter.java
app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep1Fragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/PulseFragment.java
app/src/main/java/org/gdg/frisbee/android/service/GcmIntentService.java
app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java

We were using EXTRA_CHAPTER_ID to send Parcelable Chapter somewhere and String Chapter Id elsewhere.
It is now EXTRA_CHAPTER and it always uses Chapter object.
Should also fix #286 but 100% sure

selected chapter fix

---

app/src/main/java/org/gdg/frisbee/android/adapter/NewsAdapter.java
app/src/main/java/org/gdg/frisbee/android/utils/Utils.java

This PR handles edge cases where the video url is not in the expected format and there is no app to handle the link.

Fix 301/App crashes when clicking on video

---

.travis.yml
app/build.gradle
build.gradle

I couldn't wait :)
Support library will also be needed to be updated soon. (I think)

SDK and Build tools are updated

---

app/src/main/res/layout-land/fragment_chapter_info.xml
app/src/main/res/layout-land/fragment_pulse.xml
app/src/main/res/layout/fragment_about_contributors.xml
app/src/main/res/layout/fragment_chapter_info.xml
app/src/main/res/layout/fragment_event_overview.xml
app/src/main/res/layout/fragment_events.xml
app/src/main/res/layout/fragment_gde_list.xml
app/src/main/res/layout/fragment_news.xml
app/src/main/res/layout/fragment_pulse.xml
app/src/main/res/layout/loading_animated_view.xml

Re-factored a loading animated view by creating a separate layout (`loading_animated_view.xml`) and included in layouts wherever required.

refactor: loading animated view

---

app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java
app/src/main/res/layout/fragment_event_overview.xml

Resolution for the https://github.com/gdg-x/frisbee/issues/270

Redesign event details layout

---

app/src/main/res/layout-land/fragment_pulse.xml
app/src/main/res/layout/empty.xml
app/src/main/res/layout/fragment_about_contributors.xml
app/src/main/res/layout/fragment_gde_list.xml
app/src/main/res/layout/fragment_news.xml
app/src/main/res/layout/fragment_pulse.xml

Empty view layout was already created but not used in layouts, removed redundancy from some of the layouts and have included empty view layout.

refactor: Removed redundancy and have included empty view layout

---

README.md

Do you think this enough to close #294

README includes more info about new line problem.

---

app/src/main/java/org/gdg/frisbee/android/Const.java
app/src/main/java/org/gdg/frisbee/android/activity/ArrowActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/ArrowTaggedActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/FirstStartActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/GdgNavDrawerActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/SearchActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/YoutubeActivity.java
app/src/main/java/org/gdg/frisbee/android/adapter/GdeAdapter.java
app/src/main/java/org/gdg/frisbee/android/adapter/NewsAdapter.java
app/src/main/java/org/gdg/frisbee/android/app/OrganizerChecker.java
app/src/main/java/org/gdg/frisbee/android/fragment/ContributorsFragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep1Fragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep3Fragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/InfoFragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/NewsFragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/PlainLayoutFragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/PulseFragment.java
app/src/main/java/org/gdg/frisbee/android/fragment/SettingsFragment.java
app/src/main/java/org/gdg/frisbee/android/provider/GdgProvider.java
app/src/main/java/org/gdg/frisbee/android/widget/GdgDashClockExtension.java
app/src/main/java/org/gdg/frisbee/android/widget/UpcomingEventWidgetProvider.java

I hope I didn't miss anything. I tried not to :)
Also fixes #189

chore: String constants are not actually constants.

---

.travis.yml
app/build.gradle

incremental is removed because it is dangerous. :P
textReport and textOutput to stdout is added. It will give lint errors in Travis.

Gradle config updates

---

app/src/main/AndroidManifest.xml
app/src/main/res/values-v21/gdg_themes.xml
app/src/main/res/values/gdg_themes.xml

There is no need for `Theme.GDG.NoActionBar` while all the Activities using the same theme. So we have now only `Theme.GDG`
`values-v21/gdg-themes.xml` is kept becuase it will be used for issue #335

refactor: themes

---

app/src/main/java/org/gdg/frisbee/android/appwidget/UpcomingEventWidgetProvider.java

With the event details page we always want to open the GDG app.

68/Add a default click event and always open the GDG app from app widget

---

app/src/main/java/org/gdg/frisbee/android/activity/ArrowActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/GdgNavDrawerActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/main/java/org/gdg/frisbee/android/app/OrganizerChecker.java

Don't merge this yet. 
I couldn't test most of this pull request because I cannot login to the app. I only send this for someone to review. 
Fixes #111 when merged.

Leads section improvements. 

---

app/build.gradle
build.gradle

plus: really small library updates.

update: support and play services libraries are now using a variable.

---

app/build.gradle
app/src/main/java/org/gdg/frisbee/android/about/ContributorsFragment.java
app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java
app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/chapter/NewsFragment.java
app/src/main/java/org/gdg/frisbee/android/common/GdgActivity.java
app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/EventListFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/GdgEventListFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeriesFragment.java
app/src/main/java/org/gdg/frisbee/android/gde/GdeActivity.java
app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartActivity.java
app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartStep1Fragment.java
app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java
app/src/main/java/org/gdg/frisbee/android/pulse/PulseFragment.java
app/src/main/java/org/gdg/frisbee/android/view/ColoredSnackBar.java
app/src/main/res/layout/activity_first_start.xml

Here you go with the enhancement for #365, replaced all the crouton messages with the new Snackbar.
As said earlier, I have implemented a snackbar with different colored background, e.g. red background snackbar for alert message.

Enhancement: Replace Croutons with new Snackbar

---

app/build.gradle
app/src/debug/res/values/strings.xml
app/src/main/AndroidManifest.xml

Debug suffixes added to applicationId, versionName and application name.
LeakCanary Activity label is now "GDG Leaks"

Makes the debug version installable separately.

---

app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartStep1Fragment.java
app/src/main/java/org/gdg/frisbee/android/view/ColoredSnackBar.java

Here is how it looks. It is definitely out of guidelines. By default the Action color is the accent color. When we color the background, there is only little possibility that accent color will match with red, green, blue etc. So I made it all white for all cases. 
We definitely need a RETRY button there. We can do it like below. Or we can use the standard Snackbar.

Retry button is added and duration is made infinite.

---

app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartStep2Fragment.java

With this fix app will not ask for permission again for fixes after the introduction.
Fixes #395

fix: simple fix to add Google Play Games Api to first screen.

---

app/src/main/java/org/gdg/frisbee/android/fragment/SwipeRefreshRecyclerViewFragment.java

ListFragmentSwipeRefreshLayout is a static class now with a WeakReference of the RecyclerView in the Fragment.
Since it was used in the inner class, RecyclerView was being leaked.

Memory leak fix thanks to Leak Canary.

---

app/src/main/res/values/strings.xml

Improve messaging on GDG Leads tab.

---

app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/main/java/org/gdg/frisbee/android/app/OrganizerChecker.java
app/src/main/java/org/gdg/frisbee/android/arrow/ArrowActivity.java
app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/common/GdgActivity.java
app/src/main/java/org/gdg/frisbee/android/fragment/SettingsFragment.java
app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java

This PR fixes #401 
While I was dealign with #401 I've realized that we are not updating the visibility of the leads section upon login/logout. So I've added resetOrganizer method into system.

Login Logout Fixes

---

app/src/main/java/org/gdg/frisbee/android/fragment/SwipeRefreshRecyclerViewFragment.java

I set the RecyclerView of the SwipeRefreshLayout on the wrong place. It is fixed now.
Fixes #399

This should fix scroll problems with NewsFragment

---

app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java

Adds a click listener to the title of the event page.

Add click listener on event page

---

app/src/androidTest/java/org/gdg/frisbee/android/activity/AboutActivityTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/FirstStartActivityTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/MainActivityTest.java
app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java

Use settings before launching tests, rename PrefUtils.setInitialSettings

---

app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java
app/src/main/res/values/strings.xml

This fixes up https://github.com/gdg-x/frisbee/issues/374

fix: validate inputs in feedback dialog

---

app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java

Add section for games items

---

app/src/main/java/org/gdg/frisbee/android/Const.java
app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java
app/src/main/res/values/strings.xml

Here is the PR that does the latest screenshot from me in the comment in #410 
It basically adds a new submenu. 
And I've made a quick change to `navigateTo()` function. The bundle it receives now prepopulated with the id of a selected navigation item. It will check it on the newly created Activity.

Games submenu

---

app/src/main/java/org/gdg/frisbee/android/Const.java
app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java
app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeries.java

* Fixed the Selected item on the nav drawer
* Added checks to not navigate to the same activity that we are current in
-- I followed @tasomaniac suggestions for adding the SPECIAL_EVENT id's to each one have it's own ID so we can find the items by ID

Nav Drawer Fixes

---

app/src/main/java/org/gdg/frisbee/android/arrow/ArrowTaggedActivity.java
app/src/main/java/org/gdg/frisbee/android/view/DividerItemDecoration.java
app/src/main/res/layout/activity_arrow_tagged.xml
app/src/main/res/layout/list_tagged_organizer_item.xml
app/src/main/res/values/dimens.xml

* Changed the ArrowTaggedActivity from ListView to RecyclerView
* Made the list items follow more of the design guidelines and changed cards to simple list items
* Fixed a bug that would keep making the list get populated if user hit home button and them came back to the app
* Reduced 1 layer of Overdraw by moving from CardView to a normal list
* Improved overall look of the list

* ArrowTaggedActivity Improvements / fixes

---

app/src/main/java/org/gdg/frisbee/android/api/model/LeadMessage.java
app/src/main/java/org/gdg/frisbee/android/chapter/LeadFragment.java

LeadMessage class was in Lead package but it should be in model package. Moved it there.

Move LeadMessage class into the model package

---

app/src/androidTest/java/org/gdg/frisbee/android/activity/IntentFilterTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/MainActivityDeepLinkTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/MainActivityTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/util/OrientationChangeAction.java
app/src/main/AndroidManifest.xml
app/src/main/java/org/gdg/frisbee/android/chapter/ChapterAdapter.java
app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java
app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartActivity.java
app/src/main/java/org/gdg/frisbee/android/onboarding/StartActivity.java

Some refactoring in the ChapterAdapter and how selected chapter is handled in MainActivity. 
Bug fix related to #423 ViewPager was not updating itself, because of the getItemPosition() not overriden. That's my fault. 
Wrote tests for chapter swap and orientation change. 
No UI changes. 
Fixes #423

Chapter swap fix

---

app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java

We probably don't need to make ModelCache reference to WeakReference but here I did it. 
Making Listener a weak reference and making the ASyncTask static will remove the reference of the callee. 
For example, whenever I scroll fast horizontally on About screen, Leak Canary says that ModelCache is leaking the Fragment instance. 
Now, I can scroll as fast as I can and nothing happens. 
Hopefully fix #425 and will help #424 
I know that our `ModelCache` class is fragile and actually I don't want to touch it at all. But I think it will make it better.

Converted AsyncTask implementations to static classes

---

app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartActivity.java

It should be reimplemented in Release 2.3

Actual GCM registration is removed for now.

---

app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java
app/src/main/java/org/gdg/frisbee/android/common/PeopleAdapter.java
app/src/main/java/org/gdg/frisbee/android/gde/GdeListFragment.java

Fix: Initial Load Problem and GDE List Problems

---

app/src/main/java/org/gdg/frisbee/android/arrow/ArrowActivity.java
app/src/main/java/org/gdg/frisbee/android/arrow/ArrowTaggedActivity.java
app/src/main/java/org/gdg/frisbee/android/arrow/Organizer.java
app/src/main/java/org/gdg/frisbee/android/arrow/OrganizerAdapter.java
app/src/main/res/layout/activity_arrow.xml
app/src/main/res/values/strings.xml

- Extract classes and methods out of ArrowTaggedActivity to make the code more manageable.
- This included renaming a number of variables to make them more obvious.
- Fix Accessibility issues with images on ArrowActivity.
- Fix Exception related to GoogleApiClient not being connected when calling getEncryptedMessage() in ArrowActivity.
- Fix warning about possible NPE in createNdefMessage().
- Log exceptions with Timber in ArrowActivity.
- Some of these changes are based on feedback in #431 
There is still a resource leak happening here that I haven't had time to track down, but I don't believe that it is something new introduced by these changes. Please let me know if you can see it.
org.gdg.frisbee.android.debug E/DataBuffer﹕ Internal data leak within a DataBuffer object detected!  Be …

update(arrow): Clean up Arrow code

---

app/src/main/java/org/gdg/frisbee/android/appwidget/GdgDashClockExtension.java
app/src/main/java/org/gdg/frisbee/android/appwidget/UpcomingEventWidgetProvider.java

refactor: app widget codes.

---

app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java
app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java

getUrl() used instead of getId() and manually creating Url.
If getUrl() is empty, nothing is done.
Fixes #452

id and url fields are added to the Plus Api request.

---

app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java

Fixes #453 and Crashlytics #138

Null pointer exception fix.

---

app/src/main/java/org/gdg/frisbee/android/common/GdgActivity.java
app/src/main/java/org/gdg/frisbee/android/utils/RecentTasksStyler.java

Here is how it looks. No matter what is the primary color, it will look good. 
Before | After
----|----

Recents page above Lollipop is customized with a white logo.

---

app/src/main/java/org/gdg/frisbee/android/api/PlusPersonDownloader.java
app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java
app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java

Just a duplication removal. No functionality change, no UI change.

refactor: Plus Api getPerson duplicate code is removed.

---

app/src/main/java/org/gdg/frisbee/android/achievements/Achievements.java
app/src/main/java/org/gdg/frisbee/android/api/model/Chapter.java
app/src/main/java/org/gdg/frisbee/android/api/model/Directory.java
app/src/main/java/org/gdg/frisbee/android/api/model/Gde.java
app/src/main/java/org/gdg/frisbee/android/arrow/ArrowActivity.java
app/src/main/java/org/gdg/frisbee/android/arrow/ArrowTaggedActivity.java
app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java
app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/chapter/NewsAdapter.java
app/src/main/java/org/gdg/frisbee/android/common/GdgActivity.java
app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java
app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/EventAdapter.java
app/src/main/java/org/gdg/frisbee/android/eventseries/EventListFragment.java
app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartActivity.java
app/src/main/java/org/gdg/frisbee/android/provider/GdgProvider.java
app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java
app/src/main/java/org/gdg/frisbee/android/service/GcmIntentService.java
app/src/main/java/org/gdg/frisbee/android/utils/GingerbreadLastLocationFinder.java
app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java
app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java

Thanks to lint.
Again, there should be no functional change.

Made lots of declaration access weaker.

---

.travis.yml
app/build.gradle
build.gradle

targetSdkVersion is still 22 because we need to test Runtime Permission.

dependencies and build tools are updated.

---

app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java

The PulseFragment stores the selected pulse in its arguments. The PulseActivity did always reset the spinner. 
By this PR, the activity now keeps the selected pulse in the instanceState.

449/Store selected pulse in instanceState

---

app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java
app/src/main/java/org/gdg/frisbee/android/pulse/PulseFragment.java

PulseActivity now goes back to Global on back button press.

---

app/src/main/java/org/gdg/frisbee/android/activity/ParseDeepLinkActivity.java
app/src/main/java/org/gdg/frisbee/android/arrow/OrganizerAdapter.java
app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java
app/src/main/java/org/gdg/frisbee/android/chapter/LeadFragment.java
app/src/main/java/org/gdg/frisbee/android/chapter/NewsAdapter.java
app/src/main/java/org/gdg/frisbee/android/common/PeopleListFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/EventAdapter.java
app/src/main/java/org/gdg/frisbee/android/utils/Utils.java

Introduced new utility function `createExternalIntent`
It creates and Intent with ACTION_VIEW with appropriate flags and extras.
Fixes #477 
Old screenshot can be found in #477 
It now looks like this. GDG app and Google+ are separate entities now.

Fix external Intent problem. 

---

app/src/main/java/org/gdg/frisbee/android/eventseries/EventListFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/GdgEventListFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeriesFragment.java

Only the events in the main page namely `GdgEventListFragment` should be split.

TaggedEventSeries events do not need to be split.

---

app/src/main/java/org/gdg/frisbee/android/api/model/Chapter.java
app/src/main/java/org/gdg/frisbee/android/api/model/ChapterDeserializer.java
app/src/main/java/org/gdg/frisbee/android/api/model/Contributor.java
app/src/main/java/org/gdg/frisbee/android/api/model/Country.java
app/src/main/java/org/gdg/frisbee/android/api/model/Event.java
app/src/main/java/org/gdg/frisbee/android/api/model/EventDetail.java
app/src/main/java/org/gdg/frisbee/android/api/model/GcmRegistrationRequest.java
app/src/main/java/org/gdg/frisbee/android/api/model/GcmRegistrationResponse.java
app/src/main/java/org/gdg/frisbee/android/api/model/HomeGdgRequest.java
app/src/main/java/org/gdg/frisbee/android/api/model/MessageResponse.java
app/src/main/java/org/gdg/frisbee/android/api/model/OrganizerCheckResponse.java
app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java
app/src/main/java/org/gdg/frisbee/android/chapter/ChapterComparator.java
app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartStep1Fragment.java
app/src/main/java/org/gdg/frisbee/android/utils/Utils.java

Fixes #491 
Actually there were no problems. Location is null when there is no location. It is not 0,0. 
The problem was the chapter names starting with space char. I've added a deserializer to fix that. 
While doing that, 
Unnecessary comments are removed.
Location is given in constructor to the ChapterComparator. No need to use App class in the comparator.

Location sorting fix

---

app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java

Remove the profile picture if the user is not logged in anymore.

---

app/build.gradle
build.gradle

This PR removes dependency from particular git installation and makes it easier to work on Windows

Use grgit gradle plugin for gitsha

---

app/src/main/java/org/gdg/frisbee/android/Const.java

I actually got a confirmation from Adriana about the Study Jam official dates. They will be from Feb 1st to May 1st. So enabling it on Jan 15th I think makes sense. 
I also switched to 2016 for the other events. They are approximate but I think they will be ok.

Dates are updated for event series.

---

app/src/main/java/org/gdg/frisbee/android/activity/SettingsActivity.java
app/src/main/java/org/gdg/frisbee/android/api/GapiOkHttpRequest.java
app/src/main/java/org/gdg/frisbee/android/arrow/AppStateMigrationHelper.java
app/src/main/java/org/gdg/frisbee/android/common/TrackableActivity.java

Fabric Answers analytics events are sent. 
Debug builds won't send Analytics data, they will just print to LogCat. 
AppState Migration is tracked.

Analytics improvements

---

app/src/androidTest/java/org/gdg/frisbee/android/activity/IntentFilterTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/MainActivityTest.java

Link without id does not open MainActivity in our code. Can be reverted when that functionality implemented.
MainActivity test tries to switch to Istanbul. It fails when the default chapter is not set. I set to Brussels in the beginning.

All tests are green.

---

.editorconfig
README.md

add .editorconfig file and add phrase to readme.

378/Add .editorconfig file

---

app/src/main/java/org/gdg/frisbee/android/achievements/AchievementActionHandler.java
app/src/main/java/org/gdg/frisbee/android/appwidget/GdgDashClockExtension.java
app/src/main/java/org/gdg/frisbee/android/appwidget/UpcomingEventWidgetProvider.java
app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java
app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java
app/src/main/res/values/strings.xml

- KissesFromGdgXTeam
- FeelingSocial - 2 step achievements
- Power User
achievements are fixed. 
Fixes #533

Fix 3 achievements

---

app/build.gradle
app/src/alpha/java/org/gdg/frisbee/android/app/BaseApp.java
app/src/debug/java/org/gdg/frisbee/android/app/BaseApp.java
app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/release/java/org/gdg/frisbee/android/app/BaseApp.java

Alpha version app reset code is moved to alpha build flavour folder.
BuildConfig.ALPHA is removed.

Removed old migration code that resets cache folders.

---

app/src/main/res/layout/fragment_events.xml

This commit fixes the issue #541

fix 541: center the empy state image and text

---

app/build.gradle
app/src/main/java/org/gdg/frisbee/android/activity/AppInviteDeepLinkActivity.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

Docs say that gms plugin should be applied at the end of the document. That's what I did.

Dependency updates

---

app/src/main/java/org/gdg/frisbee/android/Const.java

Fixes #567
My first PR for this repo. Please don't hesitate if I should do something differently and resubmit.

Update Wisdom Gitbook link to to 2016 version – Fixes #567

---

app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java

The additional error dialog on every app open was caused by these lines in MainActivity. 
Fixes #601

Remove old code that shows old GMS error dialog.

---

app/src/main/java/org/gdg/frisbee/android/app/GoogleApiClientFactory.java

This will allow us to disable stupid Games dialog on every login.
Also, plus scope is removed because `setRequirePlus` is enough.
The dialog is shown below. The one with animation and delaying the login process. I hate it so much :smile: :imp:

Create Games login with GameOptions.

---

app/src/main/java/org/gdg/frisbee/android/arrow/ArrowActivity.java

Fixes crash 169
http://crashes.to/s/193ec9b2727

Crash fix by adding `isContextValid` checks

---

app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/main/java/org/gdg/frisbee/android/utils/Utils.java

- Remove old OkHttp comment. OkHttp is now immutable. This explanation is no longer necessary. `clone()` method was not obvious before.
- Default implementation of Picasso is already uses the same.
- Remove unused Utils methods.

Removed some unnecessary code

---

app/src/main/java/org/gdg/frisbee/android/api/GdeDirectoryFactory.java
app/src/main/java/org/gdg/frisbee/android/api/GdgXHubFactory.java
app/src/main/java/org/gdg/frisbee/android/api/GithubFactory.java
app/src/main/java/org/gdg/frisbee/android/api/GroupDirectoryFactory.java
app/src/main/java/org/gdg/frisbee/android/api/OkClientFactory.java
app/src/main/java/org/gdg/frisbee/android/api/PlusApiFactory.java

I would say my addition of Idling Resources messed our code. I removed that utility method that injects idling resources interceptor. Instead all the OkHttpClient instances have it now. The code is cleaner.

Refactor idling resources

---

app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java

This PR fixes Crashlytics crash 263
http://crashes.to/s/61ccaa3d9b9

Fix crash related to TabLayout

---

app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java

While doing that, made some methods private.
Applied small IDE warnings.
Logged errors to crashlytics with Timber.
Fixes http://crashes.to/s/b5fd72e0102

ModelCache now catches all the possible Exceptions to prevent crash.

---

app/src/main/java/org/gdg/frisbee/android/about/AboutActivity.java
app/src/main/java/org/gdg/frisbee/android/about/AboutPagerAdapter.java
app/src/main/java/org/gdg/frisbee/android/app/BackupAgent.java
app/src/main/java/org/gdg/frisbee/android/gde/GdeActivity.java
app/src/main/java/org/gdg/frisbee/android/gde/GdeCategory.java
app/src/main/java/org/gdg/frisbee/android/gde/GdeCategoryPagerAdapter.java
app/src/main/res/layout/fragment_get_involved.xml
app/src/main/res/values/strings.xml

On the plane I've done some refactorings offline. :) 
I will explain them inline.

Various refactorings

---

app/build.gradle
app/src/androidTest/AndroidManifest.xml
app/src/androidTest/java/org/gdg/frisbee/android/activity/NotificationTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/org/gdg/frisbee/android/Const.java
app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/main/java/org/gdg/frisbee/android/arrow/NotificationHandler.java
app/src/main/java/org/gdg/frisbee/android/arrow/SummitNotificationReceiver.java
app/src/main/java/org/gdg/frisbee/android/common/GdgActivity.java
app/src/main/java/org/gdg/frisbee/android/eventseries/NotificationHandler.java
app/src/main/java/org/gdg/frisbee/android/eventseries/NotificationReceiver.java
app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeries.java
app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeriesNotificationService.java
app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml

This PR generalizes the SummitNotificationHandler and allows to show alarm notifications for all users.

Feature/256 Greetings for tagged event series

---

app/build.gradle
build.gradle

All the dependencies are updated except Play Services. They removed some deprecated classes regarding to Plus and GoogleSignIn. Once we move to new Auth, we can update it. 
The app tested manually.

Dependencies are updated

---

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Update to build tools 2.2
Update to gradle 3.1

Update to build tools 2.2

---

app/src/main/java/org/gdg/frisbee/android/Const.java
app/src/main/java/org/gdg/frisbee/android/about/ContributorsFragment.java
app/src/main/java/org/gdg/frisbee/android/app/App.java
app/src/main/java/org/gdg/frisbee/android/app/OrganizerChecker.java
app/src/main/java/org/gdg/frisbee/android/appwidget/UpcomingEventWidgetProvider.java
app/src/main/java/org/gdg/frisbee/android/cache/ModelCache.java
app/src/main/java/org/gdg/frisbee/android/chapter/ChapterSelectDialog.java
app/src/main/java/org/gdg/frisbee/android/chapter/InfoFragment.java
app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/chapter/NewsFragment.java
app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java
app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeriesFactory.java
app/src/main/java/org/gdg/frisbee/android/fragment/SettingsFragment.java
app/src/main/java/org/gdg/frisbee/android/gde/GdeActivity.java
app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartStep1Fragment.java
app/src/main/java/org/gdg/frisbee/android/provider/GdgProvider.java
app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java
app/src/main/java/org/gdg/frisbee/android/pulse/PulseFragment.java
app/src/main/java/org/gdg/frisbee/android/utils/PrefUtils.java

My intention was to kill Const class. I believe constants should be per feature. They shouldn't be available publicly to the whole app. 
Now most of them are private. 
To do that TaggedEventSeries generation is moved to its own Factory. That also made Application class leaner.

Move Constants to their related classes. 

---

app/src/main/res/layout-land/activity_special.xml
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/activity_event.xml
app/src/main/res/layout/activity_gde.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_pulse.xml
app/src/main/res/layout/activity_search.xml
app/src/main/res/layout/activity_settings.xml
app/src/main/res/layout/activity_special.xml

Added AppBarLayout to all toolbar implementations
Before | After
------ | -----
Fixes #585

Fix Toolbar elevation

---

app/src/main/java/org/gdg/frisbee/android/about/AboutActivity.java
app/src/main/java/org/gdg/frisbee/android/onboarding/AppInviteLinkGenerator.java
app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartActivity.java

AppInvite tracking
Remove non-used tracking in AboutActivity
Add tracking to sharing and installing

AppInvite tracking

---

app/build.gradle

Add untrackOld flag to play publisher
Fixes #658

Add untrackOld flag to play publisher

---

app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java

Fix null pointer exception.

---

app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java

Remove Arrow Game related login logic.

---

app/src/main/AndroidManifest.xml

Remove not needed 3 permissions

Remove not needed 3 permissions

---

app/src/main/java/org/gdg/frisbee/android/common/DrawerHeaderDisplayer.java
app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java
app/src/main/java/org/gdg/frisbee/android/common/TrackableActivity.java

Update user details when we have successful sign in
Refactor bunch of stuff in nav drawer.
We now have a special class for Header related displaying.
The real fix for #700 is just returning false in `onNavigationItemSelected`
Fixes #700

Fix: Nav drawer selection bug

---

app/src/androidTest/java/org/gdg/frisbee/android/activity/IntentFilterTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/MainActivityDeepLinkTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/MainActivityTest.java
app/src/androidTest/java/org/gdg/frisbee/android/activity/NotificationTest.java
app/src/main/res/layout/fragment_event_overview.xml

Latest changes broke the UI tests. 
I went over and fixed them.
MainActivity test was flaky because of Spinner. Now that we don't have any spinner, it is much better.

Fix UI tests

---

app/src/main/java/org/gdg/frisbee/android/api/model/Event.java
app/src/main/java/org/gdg/frisbee/android/eventseries/EventDateComparator.java
app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventDistanceComparator.java
app/src/test/java/org/gdg/frisbee/android/chapter/ChapterComparatorTest.java
app/src/test/java/org/gdg/frisbee/android/eventseries/EventDateComparatorTest.java
app/src/test/java/org/gdg/frisbee/android/eventseries/TaggedEventDistanceComparatorTest.java

Added 3 unit tests for `TaggedEventDistanceComparator`

Unit test for TaggedEventDistanceComparator

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/gdg/frisbee/android/about/AboutActivity.java
app/src/main/java/org/gdg/frisbee/android/activity/SettingsActivity.java
app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java
app/src/main/java/org/gdg/frisbee/android/chapter/NewsAdapter.java
app/src/main/java/org/gdg/frisbee/android/common/GdgActivity.java
app/src/main/java/org/gdg/frisbee/android/common/GdgNavDrawerActivity.java
app/src/main/java/org/gdg/frisbee/android/event/EventActivity.java
app/src/main/java/org/gdg/frisbee/android/event/EventOverviewFragment.java
app/src/main/java/org/gdg/frisbee/android/eventseries/TaggedEventSeriesActivity.java
app/src/main/java/org/gdg/frisbee/android/gde/GdeActivity.java
app/src/main/java/org/gdg/frisbee/android/onboarding/FirstStartActivity.java
app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java
app/src/main/res/layout-land/fragment_welcome_step1.xml
app/src/main/res/layout-land/fragment_welcome_step2.xml
app/src/main/res/layout/actionbar_chapter_selector.xml
app/src/main/res/layout/actionbar_spinner.xml
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/fragment_welcome_step1.xml
app/src/main/res/layout/spinner_item_actionbar.xml
app/src/main/res/layout/toolbar_actionbar.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rPT/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values/gdg_themes.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

http://crashes.to/s/37485207d95
I noticed a crash in settings. This happens when both GdgActivity and SettingsActivity tries to sign in the user at the same time.
While doing this I refactor all the creation/handling of ActionBar/Toolbars in the app. 
Also now we have the default title style from AppCompat everywhere.

Fix crash in settings
